#!/bin/sh
# This test can be run by hand to check if the install page still works
# @todo turn this into a behat test that checks output and existence of database tables/records

# Clear database
    MYSQL_BIN="mysql --defaults-extra-file=$HOME/my.cnf"
    echo 'drop database if exists janus_install_test'  | $MYSQL_BIN
    echo 'create database janus_install_test CHARSET=utf8 COLLATE=utf8_unicode_ci'  | $MYSQL_BIN

# Post install values
    curl \
    --insecure \
    -X POST \
    --data "action=install&admin_email=admin@example.com&admin_name=Admin&dbhost=localhost&dbname=janus_install_test&dbpass=c0n3xt&dbprefix=janus__&dbtype=mysql&dbuser=root&submit_admin_user=Install" \
    https://serviceregistry.demo.openconext.org/simplesaml/module.php/janus/install/