_welcome:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: janus_legacy
        permanent: true # this for 301
        prefix: /janus/pages/app_ssp.php/


_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /janus/pages/app_ssp.php/_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /janus/pages/app_ssp.php/_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /janus/pages/app_ssp.php/_configurator

_main:
    resource: routing.yml
