_welcome:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: get_connections
        permanent: true # this for 301

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

_snapshots:
  resource: @JanusServiceRegistryRestApiBundle/Resources/config/routing_dev.yml
  prefix:   /api
