janus_connection_rest:
    type:     rest
    resource: "@JanusServiceRegistryRestApiBundle/Controller/ConnectionController.php"

janus_snapshot_rest:
    type:     rest
    resource: "@JanusServiceRegistryRestApiBundle/Controller/SnapshotController.php"